#!/bin/bash
# chkconfig: 35 80 70
# description: service zimg
PATH=/usr/local/bin:/sbin:/usr/bin:/bin
EXEC=/usr/local/zimg/bin/zimg 
CONF="/usr/local/zimg/bin/conf/zimg.lua"

case "$1" in

	start)
		echo "Starting Zimg server..."
		$EXEC $CONF
		;;
	stop)
		pkill zimg
		;;
esac

