#!/bin/bash
# chkconfig:   2345 90 90
# description: Tcp service manager
 
PHP=/usr/bin/php
SCRIPT=/data/www/yun_new/start.php
PIDFILE=/tmp/yun_work.master.pid

case "$1" in
        start)
                if [ -f $PIDFILE ]
                then
                        echo "$PIDFILE exists, process is already running or crashed."
                else	
                        echo "Starting TCP server..."
                        $PHP $SCRIPT start
                fi
                if [ "$?"="0" ]
                then
                        echo "TCP server is running..."
                fi
                ;;
        stop)
                if [ ! -f $PIDFILE ]
                then
                        echo "process is not running."
                else
                        PID=$(cat $PIDFILE)
                        echo "Stopping..."
                        $PHP $SCRIPT stop
                        while [ -x $PIDFILE ]
                        do
                                echo "Waiting for TCP server to shutdown..."
                                sleep 1
                        done
                        echo "TCP server stopped"
                fi
                ;;
	status)
		if [ ! -f $PIDFILE ]
                then
                        echo "process is not running."
                else
                        $PHP $SCRIPT status
                fi
                ;;
        restart)
                ${0} stop
                ${0} start
                ;;
        *)
                echo "Usage: /etc/init.d/yun {start|stop|restart}" >&2
                exit 1
esac

